# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_db_subnet_group.main
#
# WHY WAS THIS CREATED?
#
# This Db Subnet Group was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_db_subnet_group" "main" {
  name = "main-db-subnet-group"
  subnet_ids = [aws_subnet.private_1.id, aws_subnet.private_2.id]
  tags = {
    Name = "main-db-subnet-group"
  }
}

# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_security_group.rds
#
# WHY WAS THIS CREATED?
#
# This Security Group was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_security_group" "rds" {
  name = "rds-security-group"
  description = "Security group for RDS PostgreSQL"
  vpc_id = aws_vpc.main.id
  ingress {
    from_port = 5432
    to_port = 5432
    protocol = "tcp"
    cidr_blocks = ["10.0.0.0/16"]
  }
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    Name = "rds-security-group"
  }
}

# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_db_instance.postgres
#
# WHY WAS THIS CREATED?
#
# This Db Instance was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_db_instance" "postgres" {
  identifier = "postgres-db"
  engine = "postgres"
  engine_version = "15.4"
  instance_class = "db.t3.micro"
  allocated_storage = 20
  storage_type = "gp2"
  db_name = "postgres"
  username = "postgres"
  password = "changeme123!"
  db_subnet_group_name = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  skip_final_snapshot = true
  tags = {
    Name = "postgres-db"
  }
}
