# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_subnet.db_1
#
# WHY WAS THIS CREATED?
#
# This Subnet was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_subnet" "db_1" {
  vpc_id = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
  availability_zone = "us-east-1a"
  map_public_ip_on_launch = true
  tags = {
    Name = "db_1"
    ManagedBy = "Kyrna"
  }
}

# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_subnet.db_2
#
# WHY WAS THIS CREATED?
#
# This Subnet was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_subnet" "db_2" {
  vpc_id = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
  availability_zone = "us-east-1a"
  map_public_ip_on_launch = true
  tags = {
    Name = "db_2"
    ManagedBy = "Kyrna"
  }
}
