# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_vpc.main
#
# WHY WAS THIS CREATED?
#
# This Vpc was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support = true
  tags = {
    Name = "main-vpc"
  }
}

# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_subnet.private_1
#
# WHY WAS THIS CREATED?
#
# This Subnet was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_subnet" "private_1" {
  vpc_id = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
  availability_zone = "us-west-2a"
  tags = {
    Name = "private-subnet-1"
  }
}

# ============================================================================
# GENERATED by Kyrna AI
# ============================================================================
# Resource: aws_subnet.private_2
#
# WHY WAS THIS CREATED?
#
# This Subnet was generated based on your request.
# It follows AWS best practices and is configured for production use.
#
# 📝 NOTE: This file was auto-generated by Kyrna AI.
#          Review the configuration and modify as needed for your environment.
#          You can undo this change if you have existing infrastructure.
# ============================================================================

resource "aws_subnet" "private_2" {
  vpc_id = aws_vpc.main.id
  cidr_block = "10.0.2.0/24"
  availability_zone = "us-west-2b"
  tags = {
    Name = "private-subnet-2"
  }
}
